[workspace]

members = [
    "crates/flv",
    "crates/flv-fix",
    "crates/aac",
    "crates/bytes-util",
    "crates/expgolomb",
    "crates/av1",
    "crates/h265",
    "crates/h265",
    "crates/amf0",
]

[package]
name = "rust-srec"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
byteorder = "1.5.0"
kanal = "0.1"
criterion = "0.5"
tokio = { version = "1.36", features = ["full"] }

[[bench]]
name = "test_channels"
harness = false