[workspace]

members = [
    "crates/flv",
    "crates/aac",
    "crates/bytes-util",
    "crates/expgolomb",
    "crates/av1",
    "crates/h265",
    "crates/h265",
]

[package]
name = "rust-srec"
version = "0.1.0"
edition = "2024"

[dependencies]
