[package]
name = "amf0"
version = "0.1.1"
edition = "2024"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[dependencies]
bytes = "1.10.1"
byteorder = "1.5"
num-traits = "0.2"
num-derive = "0.4"
thiserror = "2.0"
