[package]
name = "expgolomb"
version = "0.1.1"
edition = "2024"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }


[dependencies]
bytes-util = { path = "../bytes-util" }

[dev-dependencies]
bytes = "1.10.1"
