[package]
name = "flv"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
byteorder = "1.5.0"
tokio = { version = "1.36", features = ["full"] }
futures = "0.3"
bytes-util = {path = "../bytes-util"}